version: 2
jobs:
  test:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run: bundle install
      - run: carthage update --platform ios --use-xcframeworks
      - run:
          name: "単体テスト"
          command: "bundle exec fastlane unittest"

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
