default_platform(:ios)

platform :ios do
  before_all do |lane, options|
    setup_circle_ci
  end
  before_each do |lane, options|
    puts("before_each (lane: #{lane})")
  end
  after_each do |lane, options|
    puts("after_each (lane: #{lane})")
  end
  after_all do |lane, options|
    puts("after_all (lane: #{lane})")
  end

  lane :unittest do
    scan --scheme "CorporateAnalysisHubAPPTests"
  end
end
