# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  xcode_select("/Applications/Xcode-13.4.1.app")
  desc "Debugビルド"
  lane :build do
    build_ios_app(
      scheme: "CorporateAnalysisHubAPP",
      configuration: "Debug")
  end

  lane :unittest do
    run_tests(
      scheme: "CorporateAnalysisHubAPP",
      configuration: "Debug"
    )
  end
end
